### Create a tag
POST http://localhost:3000/tag-create HTTP/1.1
Content-Type: application/json

{
  "key": "cpp",
  "name": "C++"
}

### Create another tag
POST http://localhost:3000/tag-create HTTP/1.1
Content-Type: application/json

{
  "key": "sdl",
  "name": "SDL"
}

### Create a content
# @name CreateContent1
POST http://localhost:3000/content-create HTTP/1.1
Content-Type: application/json

{
  "type": "BLOG",
  "title": "This is a Blog Article",
  "tagKeys": [
    "sdl"
  ],
  "summary": "Record every bit of my life",
  "content": "Today I have to finish the work in hand!"
}

@contentId1 = {{CreateContent1.response.body.$.data.newContentId}}

### Create another content
# @name CreateContent2
POST http://localhost:3000/content-create HTTP/1.1
Content-Type: application/json

{
  "type": "PAGE",
  "title": "This is a Normal Page",
  "tagKeys": [
    "cpp"
  ],
  "summary": "Record every bit of my life",
  "content": "Today I have to finish the work in hand!"
}

@contentId2 = {{CreateContent2.response.body.$.data.newContentId}}

### Get a content with its ID
POST http://localhost:3000/content-get?id={{contentId1}} HTTP/1.1

### List all contents without any filters
POST http://localhost:3000/content-list?sort=created_at&order=DESC&take=5&skip=0 HTTP/1.1

### List contents according to match results
POST http://localhost:3000/content-list?q=Blog Article Life&sort=score&order=DESC&take=5&skip=0 HTTP/1.1

### Update a content with its ID
POST http://localhost:3000/content-update?id={{contentId1}} HTTP/1.1
Content-Type: application/json

{
  "type": "BLOG",
  "title": "This is an Updated Blog Article",
  "tagKeys": [
    "cpp",
    "sdl"
  ],
  "summary": "A short C++ tutorial to setup SDL in a C++ project",
  "content": "..."
}

### List contents according to tags
POST http://localhost:3000/content-list?tag=sdl&tag=cpp&sort=created_at&order=DESC&take=5&skip=0 HTTP/1.1

### Delete a content
POST http://localhost:3000/content-delete?id={{contentId1}} HTTP/1.1

### Delete another content
POST http://localhost:3000/content-delete?id={{contentId2}} HTTP/1.1

### Delete a tag
POST http://localhost:3000/tag-delete?key=cpp HTTP/1.1

### Delete another tag
POST http://localhost:3000/tag-delete?key=sdl HTTP/1.1
