### Create a content
# @name CreateContent1
POST http://localhost:3000/content-create HTTP/1.1
Content-Type: application/json

{
  "type": "BLOG",
  "title": "This is a Blog Article",
  "createdAt": "2024-07-17 20:40:00",
  "updatedAt": "2024-07-17 21:00:00",
  "tagKeys": [],
  "summary": "Record every bit of my life",
  "content": "Today I have to finish the work in hand!"
}

@contentId1 = {{CreateContent1.response.body.$.data.newContentId}}

### Create another content
# @name CreateContent2
POST http://localhost:3000/content-create HTTP/1.1
Content-Type: application/json

{
  "type": "PAGE",
  "title": "This is a Normal Page",
  "createdAt": "2024-07-16 22:40:00",
  "updatedAt": "2024-07-16 21:00:00",
  "tagKeys": [],
  "summary": "Record every bit of my life",
  "content": "Today I have to finish the work in hand!"
}

@contentId2 = {{CreateContent2.response.body.$.data.newContentId}}

### Create a page
POST http://localhost:3000/page-create HTTP/1.1
Content-Type: application/json

{
  "key": "contact",
  "menuName": "Contact Us",
  "contentId": "{{contentId1}}"
}

### Create another page
POST http://localhost:3000/page-create HTTP/1.1
Content-Type: application/json

{
  "key": "profile",
  "menuName": "About Us",
  "contentId": "{{contentId2}}"
}

### Get a page with its key
POST http://localhost:3000/page-get?key=contact HTTP/1.1

### Update a page with its key
POST http://localhost:3000/page-update?key=contact HTTP/1.1
Content-Type: application/json

{
  "menuName": "Contact Us Immediately",
  "contentId": "{{contentId2}}"
}

### List all pages
POST http://localhost:3000/page-list HTTP/1.1

### Delete a page
POST http://localhost:3000/page-delete?key=contact HTTP/1.1

### Delete another page
POST http://localhost:3000/page-delete?key=profile HTTP/1.1

### Delete a content
POST http://localhost:3000/content-delete?id={{contentId1}} HTTP/1.1

### Delete another content
POST http://localhost:3000/content-delete?id={{contentId2}} HTTP/1.1
