###
POST http://localhost:3000/tag-create HTTP/1.1
Content-Type: application/json

{
  "key": "cpp",
  "name": "C++"
}

###
POST http://localhost:3000/tag-create HTTP/1.1
Content-Type: application/json

{
  "key": "sdl",
  "name": "SDL"
}

###
POST http://localhost:3000/tag-get?key=cpp HTTP/1.1
Content-Type: application/json

###
POST http://localhost:3000/tag-list HTTP/1.1
Content-Type: application/json
