services:
  objstorage:
    image: quay.io/minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=no-password
      - MINIO_DEFAULT_BUCKETS=website_test